# Development Mode
# Use:
# docker-compose -f docker-compose.dev.yml run
burden:
  extends:
    file: docker-compose.yml
    service: burden
  volumes:
    - ./burden:/opt/app/burden
  command: nodemon --watch ./burden --exec "npx colloquist server"